# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-25 03:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='picture',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='referral_link',
            field=models.UUIDField(editable=False, null=True, verbose_name='referral_link'),
        ),
        migrations.AlterField(
            model_name='student',
            name='referrer_students',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Student'),
        ),
    ]
