# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-25 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180225_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categorie', to='core.Categorie'),
            preserve_default=False,
        ),
    ]
