# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-25 22:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_comment_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.CharField(default='def', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notationhistory',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='core.Student'),
        ),
    ]
