# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-27 16:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180227_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notationhistory',
            name='month',
        ),
    ]
