# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-27 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_notationhistory_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='current_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
