# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-27 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_student_current_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='current_score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
