# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-27 22:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20180227_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notationhistory',
            name='choice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='core.Choice'),
        ),
    ]
