# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-27 23:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20180227_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='notationhistory',
            name='month',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='notationhistory',
            name='year',
            field=models.IntegerField(default=2018),
        ),
        migrations.AlterField(
            model_name='notationhistory',
            name='choice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notations', to='core.Choice'),
        ),
    ]
