# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-27 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20180227_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='last_month_vote',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='student',
            name='last_year_vote',
            field=models.IntegerField(default=2018),
        ),
    ]
