# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-01 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20180301_0352'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='_validation_str',
            field=models.CharField(default='MKLJDLQN7X4PTIAIV8NA7JU6IEG4OVNJCGAD7F2CKJ6PVJ59B6NAH7AQ4PJARCMLM5Y8EGCK79NLFEYGYT5NS1DF2LTU0DR3CIVL', editable=False, max_length=100, verbose_name='Validation string'),
        ),
        migrations.AlterField(
            model_name='student',
            name='referral_link',
            field=models.CharField(default='5ZVL53PDH8G8RTIAL6N8WLGP5YH6058YYZ0E5MZQA87QL0Y2286E84HW0A1LZ09U1J5UGKJA9ASIEIX85VJGA8G20ISZB8DZ6HHJ', editable=False, max_length=100, verbose_name='referral_link'),
        ),
    ]
