# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-07 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20180303_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image_link',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='_validation_str',
            field=models.CharField(default='5VYV4A6BZ91K0HRM0N3322N0QYR4VPJ8E5XCDOP3OAK260KRHFP0ULU3TJ2SQ5Z8TIW1DAWBI71MJN3EZ3FPNKTRFA3WV6UOSW00', editable=False, max_length=100, verbose_name='Validation string'),
        ),
        migrations.AlterField(
            model_name='student',
            name='referral_link',
            field=models.CharField(default='CUT2RM73EH5MN7VU35C7F15A6WGKBTRPAFIC9QSNDZ07K1OESNJON0H5W0TMLG7CQNWI89HYL15AYXNFVIHRT5I8151HGX2O4GIM', editable=False, max_length=100, verbose_name='referral_link'),
        ),
    ]
