# Generated by Django 2.0.3 on 2018-04-08 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20180310_0421'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='comments',
            field=models.TextField(default='Comment content', null=True),
        ),
        migrations.AlterField(
            model_name='notationhistory',
            name='month',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='student',
            name='_validation_str',
            field=models.CharField(default='ZFA7G167OKZWKOLCTG6RB6B1JQUKY48URKERH8B8D51H8ARA5R0TUVLXYKSZANJGLNGMP0IL4N1WINZQHE4SVX5ZM06R6FU4G767', editable=False, max_length=100, verbose_name='Validation string'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_month_vote',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='student',
            name='referral_link',
            field=models.CharField(default='DVBY0DP8HNC95ONGQE0MJVIRR30VTTF18N3RKV1K486VJVBD6FGF0SJ37BPZH9QCOOF2BEGQHWPRRIWEC3Y5EOUY0XW52OKWNH92', editable=False, max_length=100, verbose_name='referral_link'),
        ),
    ]
